steps:

  - name: node:16
    entrypoint: yarn
    env:
      - NODE_ENV=dev
    args: [ 'install' ]

  - name: node:16
    entrypoint: yarn
    env:
      - CONFIG_ENV=dev
    args: [ 'build' ]

  - name: gcr.io/$PROJECT_ID/firebase
    args: [ 'deploy', '--project=$PROJECT_ID', '--only=hosting' ]


timeout: "600s"
